//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_Subscribe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrator
    {
        public int admID { get; set; }
        public string admName { get; set; }
        public string admCorp { get; set; }
        public string admDep { get; set; }
        public string admMail { get; set; }
        public string admExt { get; set; }
        public string admAccount { get; set; }
        public string admPassword { get; set; }
        public string admAuthority { get; set; }
        public int admEnabled { get; set; }
        public System.DateTime admCreateDate { get; set; }
        public Nullable<System.DateTime> admLastModify { get; set; }
    }
}
