//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_Subscribe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminGroup
    {
        public int authID { get; set; }
        public int authCode { get; set; }
        public string authText { get; set; }
        public int authEnabled { get; set; }
        public string authMenuAuth { get; set; }
        public string authFuncAuth { get; set; }
        public string authCreateDate { get; set; }
        public string authLastModify { get; set; }
    }
}
