//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_Subscribe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminAuthGroup
    {
        public int agID { get; set; }
        public string agName { get; set; }
        public int agRank { get; set; }
        public string agContent { get; set; }
        public string agCreateDate { get; set; }
        public string agLastModify { get; set; }
        public int agEnabled { get; set; }
    }
}
