//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_Subscribe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int mID { get; set; }
        public string mName { get; set; }
        public string mBirthday { get; set; }
        public string mSocialSecurityCode { get; set; }
        public int mGender { get; set; }
        public string mTelHome { get; set; }
        public string mTelOffice { get; set; }
        public string mTelOfficeExt { get; set; }
        public string mMobile { get; set; }
        public string mMail { get; set; }
        public string mZip { get; set; }
        public string mAddressCity { get; set; }
        public string mAddressArea { get; set; }
        public string mAddressRest { get; set; }
        public string mCreditCardNo { get; set; }
        public string mCreditCardExp { get; set; }
        public string mCreditCardCVV { get; set; }
        public int mEnabled { get; set; }
        public string mAddDate { get; set; }
        public string mLastModify { get; set; }
    }
}
