//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_Subscribe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MITEM
    {
        public decimal auto_id { get; set; }
        public string mitcode { get; set; }
        public string ditcode { get; set; }
        public string ddesc { get; set; }
        public string rank { get; set; }
        public string FaxNum { get; set; }
        public string View_tag { get; set; }
        public string Fax_tag { get; set; }
        public string Sys_tag { get; set; }
        public string Product_tag { get; set; }
        public string del_tag { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
    }
}
